### ISSUE TITLE
New animated gif for latest version

### ISSUE THREAD

**Issue by MattMcFarland** [trainyard/choo-cli#11]
Latest version has a prettier interface, including some ascii art of a choo-choo train.  Would be nice to show that in the gif demo :)

**Comment by ronnross** [comment]
I will work on this!

**Comment by MattMcFarland** [comment]
Lookin good! Any chance you can increase the time around the ascii art by 300-600ms ??

**Comment by ronnross** [comment]
sure thing! Director's cut coming up.

**Comment by ronnross** [comment]
Updated.
