### ISSUE TITLE
Replace nodegit with a more stable solution

### ISSUE THREAD

**Issue by MattMcFarland** [trainyard/choo-cli#115]
[nodegit](https://github.com/nodegit/nodegit) is causing some installation errors, as mentioned in issues #114 and #105 

We need to remove and replace it with something which does the same thing (git clone basically) to avoid the installation problem.

If anyone picks this issue up, please assign it to yourself.

**Comment by IzumiSy** [comment]
`git-js` could be an alternative to nodegit: https://github.com/steveukx/git-js

**Comment by IzumiSy** [comment]
For more information, currently, choo-cli uses `nodegit` just mainly to execute 'clone' from this line.
https://github.com/trainyard/choo-cli/blob/58553b2447fd181f38028ce5189e3bb2fea79805/lib/genus.js#L54-L96

**Comment by MattMcFarland** [comment]
Looking at `gitClone` which is a promise, and seeing how the `then()` passes nothing, it seems we make an assumption that the template was clone into a specific directory (which isnt clear to me briefly looking at the code that i wrote a long time ago LOL).  If we use `git-js` (or anything else) and use the same pattern it could be a drop in replacement!  That is of course there aren't other assumptions hiding in the code.  

I now wish that `gitClone` .then passed in the filepath where the template was cloned now too.  This is the benefit from looking at ones old code heh.
