### ISSUE TITLE
'choo new' command is not recognized

### ISSUE THREAD

**Issue by varvarasd** [trainyard/choo-cli#117]
However I've discovered that running `choo-new my-choo-app` works just fine but in the instructions it's mentioned to run `choo new my-choo-app`

![cap1](https://user-images.githubusercontent.com/21359557/38171922-e32923f2-359a-11e8-9a4f-f6c574f309ee.JPG)

**Comment by MattMcFarland** [comment]
`choo new` should work, as it runs`choo-new` internally - this looks like a bug (windows specific) - Can you edit the file that spawns `choo-new` by chance?  It might be worth logging out env vars to see if something is missing.

**Comment by varvarasd** [comment]
the command `choo new my-choo-app` worked after I installed cygwin and yarn.
I'll keep you posted if anything new pops up.
many thanks!
