### ISSUE TITLE
Local dev server crashes when it's opened in the browser

### ISSUE THREAD

**Issue by varvarasd** [trainyard/choo-cli#118]
So after runnint `npm start` I'm getting this 
![choo-1](https://user-images.githubusercontent.com/21359557/38199152-83bcf824-3687-11e8-8c44-e1f92f70ac61.JPG)

As soon as I open localhost in the browser it crashes like so 
![choo-2](https://user-images.githubusercontent.com/21359557/38199169-9f37af4a-3687-11e8-8485-39df06ab61d4.JPG)

After the crash, seems that bankai keeps reloading:
![choo-3](https://user-images.githubusercontent.com/21359557/38200032-ba533864-368a-11e8-87b3-c45b136e75f3.JPG)

Sometimes after running `npm start` it just exits the cmd.

Any suggestions?

Thanks!

**Comment by MattMcFarland** [comment]
It looks like a permissions issue (the running node app doesnt have permission to work on the file system) - This probably doesnt work with windows.  Have you tried using cygwin and yarn? You would have to restart your project though in that environment.

**Comment by varvarasd** [comment]
the command `choo new my-choo-app` worked after I installed cygwin and yarn.
I'll keep you posted if anything new pops up.
many thanks!
