### ISSUE TITLE
Add choo badge to the generated readme file

### ISSUE THREAD

**Issue by MattMcFarland** [trainyard/choo-cli#12]
Add the choo badge to the generated readme file found in `generators/app/template`

``` markdown
[![built with choo v3](https://img.shields.io/badge/built%20with%20choo-v3-ffc3e4.svg?style=flat-square)](https://github.com/yoshuawuyts/choo)
```

Which looks like this:

[![built with choo v3](https://img.shields.io/badge/built%20with%20choo-v3-ffc3e4.svg?style=flat-square)](https://github.com/yoshuawuyts/choo)

**Comment by ronnross** [comment]
Resolved with commit 4799eb2
