### ISSUE TITLE
Add style example to generated project?

### ISSUE THREAD

**Issue by ronnross** [trainyard/choo-cli#17]
### Expected behavior

I personally would like to see an example of a stylesheet being used in the generated project.

I understand we probably don't want to force someone into using [sheetify](https://github.com/stackcss/sheetify), but would it be better to provide some sort of example? I asked myself these questions and wanted to see how other's feel.

Do most other cli projects include styles?
Is it easier to remove them or add them ?
### Actual behavior

No css being used in currently generated project. 
### Steps to reproduce behavior

run `choo new <project>`

**Comment by YerkoPalma** [comment]
I think that the best option would be that the generator ask about devs opinion. Something like

``` bash
$ would you like to use sheetify (y/n)? y
```

And with inquirer manage the user option

**Comment by ronnross** [comment]
We'll be using this for the 1.0 release.

**Comment by MattMcFarland** [comment]
Rather than asking, we think it would be best to use `from` to grab a template with sheetify.

**Comment by YerkoPalma** [comment]
I agree. Also, I think that a more solid _asking_ default template would be great, and the capability to define custom options to ask about also, but all that would be for a major release, e.g. 2.0 release.

**Comment by ronnross** [comment]
I really like that option. I'm going to try and reject my pull request
since we have a better option.

**Comment by YerkoPalma** [comment]
Then this issue can be closed?

**Comment by ronnross** [comment]
Yeah I'm going to close this issue.
