### ISSUE TITLE
Generators doesn't validate names

### ISSUE THREAD

**Issue by YerkoPalma** [trainyard/choo-cli#29]
### Expected behavior

Should add only valid functions in generators
### Actual behavior

Doesn't validate, so it generate functions that will throw exceptions
### Steps to reproduce behavior

In any choo generated project run 

``` bash
$ choo generate page 404
```

and will generate a file exporting a `function 404 ()` which is invalid

**Comment by MattMcFarland** [comment]
good find!

**Comment by YerkoPalma** [comment]
It seems that _valid names_ for javascript functions isn't that trivial. According to [this reference](http://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names) there is a complex regex validation that can be done. Also notice that there is different rules fro ECMAScript 5 and ECMAScript 6. So I propose that we can be more restrictives in this, and define our own set of rules for valid generator names.

**ref**
- https://mathiasbynens.be/notes/javascript-identifiers-es6

**Comment by MattMcFarland** [comment]
We could parse the AST isntead of using regex

**Comment by MattMcFarland** [comment]
@YerkoPalma I believe I've fixed this with the latest version, you can try it by installing rc2:

```
npm install choo-cli@v1.0.0-rc2 -g
```

please have a look and let me know!!!

Thanks,
Matt

**Comment by MattMcFarland** [comment]
Tests I have indicate this is working, so I'll close it for now.
