### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by MattMcFarland** [trainyard/choo-cli#39]
### Expected behavior
Build should pass

### Actual behavior
Build fails

### Steps to reproduce behavior
run `npm test` - need to fix unit tests!

**Comment by rollymaduk** [comment]
I think the errors you are getting are style related enforced by standard package, and you can fix most of the errors by running standard with --fix option in your package.json

> standard: Use JavaScript Standard Style (http://standardjs.com)
> standard: Run `standard --fix` to automatically fix some problems.
> /home/travis/build/trainyard/choo-cli/bin/choo-generate.js
>   15:31  error  Extra semicolon
>   19:59  error  Extra semicolon
>   29:29  error  Extra semicolon
>   30:41  error  Extra semicolon
>   47:1   error  More than 1 blank line not allowed
>   51:63  error  Extra semicolon
> /home/travis/build/trainyard/choo-cli/generators/app/index.js
>   32:54  error  Block must not be padded by blank lines
>   78:39  error  Extra semicolon
>   80:3   error  Expected space or tab after '//' in comment

**Comment by MattMcFarland** [comment]
Yes, true that, there should be some failing unit tests though (unless I removed them)
