### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by MattMcFarland** [trainyard/choo-cli#5]
`[EDIT]: Need to add unit tests and cover this cli project`
- verify the files are created as expected.
- verify directory structure is generated
- verify generators

**Comment by YerkoPalma** [comment]
You mean to add tests to the cli project or the generated choo project?

**Comment by MattMcFarland** [comment]
This would be unit testing around the cli project.  For now I think we will leave unit tests out of generated project to keep things simple, although I do like the idea of adding them.

**Comment by YerkoPalma** [comment]
I just saw this [clinton project](https://github.com/SamVerschueren/clinton) and I think it could work for this tests, because all the tests described are about project integrity, just what Clinton does. It might worht to take a look

**Comment by MattMcFarland** [comment]
Nice!! I'll check it out.

**Comment by MattMcFarland** [comment]
Added unit tests, closing (but feel free to reopen if need be)
