### ISSUE TITLE
Add an option to use yarn

### ISSUE THREAD

**Issue by Haroenv** [trainyard/choo-cli#56]
### Expected behavior
Be able to use yarn instead of npm

### Actual behavior
choo-cli always installs with npm

### Steps to reproduce behavior
`choo new`

### Details

So as in https://github.com/trainyard/choo-cli/pull/54, I'd prefer to use yarn instead of npm, but of course in a new folder you can't implicitly check out if it's yarn. I guess a `--yarn` argument would make sense in this case, since there isn't a global configuration object or something like that. 

If that's considered out of scope, a flag to disable installing would be the closest thing to what I want.

**Comment by ronnross** [comment]
OK, let me play around with this. Thanks!

**Comment by MattMcFarland** [comment]
Added this feature just as you suggested `--yarn` , added documentation as well.
