### ISSUE TITLE
Add a list of existing generators

### ISSUE THREAD

**Issue by Haroenv** [trainyard/choo-cli#57]
* [trainyard/template-basic](https://github.com/trainyard/template-basic)
* [haroenv/template-webpack](https://github.com/haroenv/template-webpack)
* ...

**Comment by ronnross** [comment]
Great idea! I will set this up.

**Comment by ronnross** [comment]
@Haroenv with commit 09cdf60 I added a markdown file in listOfGenerators/generators.md. It is linked off of the main README.md. This was a way to get the idea quickly in place. Folks and add their generator to the file with a PR. If we see a lot of generators then maybe we can make a separator page with search. Your thoughts?

**Comment by Haroenv** [comment]
That looks good to me, are there no other generators you know of?

**Comment by ronnross** [comment]
Not yet, but I will put the word out, and I'm planning on making at least two more.  I'm going to close this for now. Thanks for the idea!
