### ISSUE TITLE
Demo App uses wrong property

### ISSUE THREAD

**Issue by allthesignals** [trainyard/choo-cli#74]
### Expected behavior
Demo app should return value of input

### Actual behavior
It returns nothing (probably undefined)

### Steps to reproduce behavior
Running node v6.10.0. Just generate a new app. I'm not sure where this code lives, otherwise I'd try to fix it, but this:

```
    update: function (state, data) {
      return { title: data.value }
    }
```

needs to change to:
```
    update: function (state, data) {
      return { title: data }
    }
```

**Comment by IzumiSy** [comment]
Hi, you might be able to open a pull request to make a change to the default choo-cli template: https://github.com/trainyard/template-basic. Could you check this out?

**Comment by MattMcFarland** [comment]
I believe this was fixed 20 days ago, so I'm going to close it out.. Please post issues regarding the template at https://github.com/trainyard/template-basic/issues
